import os
import subprocess


def run_python_file(working_directory, file_path, args=[]):
    abs_working_directory = os.path.abspath(working_directory)
    #print(f"Working directory: {abs_working_directory}")
    abs_file_path = os.path.abspath(os.path.join(abs_working_directory, file_path))
    #print(f"Requested file path: {abs_file_path}")
    
    if not abs_file_path.startswith(abs_working_directory):
        return f'Error: Cannot execute "{file_path}" as it is outside the permitted working directory'
    
    if not os.path.isfile(abs_file_path):
        return f'Error: "{file_path}" does not exist or is not a regular file'
    
    if not abs_file_path.endswith('.py'):
        return f'Error: "{file_path}" is not a Python file'
    
    try:
        final_args = ['python3', abs_file_path]
        final_args.extend(args)
        output = subprocess.run(final_args, timeout=30, check=True, capture_output=True, text=True, cwd=abs_working_directory)
        
        final_string = f"""  
    STDOUT:{output.stdout}
    STDERR:{output.stderr}
    """
        if output.returncode != 0:
            final_string += f"Error: Process exited with code {output.returncode}\n"
        
        
        if output.stdout == "" and output.stderr == "":
            final_string +=  f"Error: No output generated by the script\n"
        
        return final_string
        
    except Exception as e:
        return f"Error: Execution of {file_path} failed with error: {e}"